### ISSUE TITLE
[CUSA07010]: Sonic Mania

### ISSUE THREAD

**Issue by igor725** [SysRay/psOff_compatibility#4] opened 2024-04-07 23:03 UTC
### Please, describe what you get

The game seems to work fine, visuals are ok, but it won't save progress and options

### Game version you are using

v1.0

### Current game status

Ingame

### Version

v.0.4-beta (Default)

### psOff-libs version you are using

0a845da6825bb256a84ff918caa699fbfb70a4a9

### Upload your log there

[20240408-015829.000.zip](https://github.com/SysRay/psOff_compatibility/files/14899297/20240408-015829.000.zip)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by cainan-c** [comment] 2024-04-18 16:25
### Please, describe what you get
Appears that the game should be playable from start to finish now. Saving works, graphically the game is mostly fine.
Using the newest psOff-libs does cause the colours in-game to appear more washed out than in previous versions.
All screen mode filters but "None" work as intended.

Currently, any multiplayer modes (such as Competition Mode or Player 2 controlling Tails in Mania Mode) do not work, as any controller other than the 1st isn't currently recognised.

### Game version you are using

v01.00

### Current game status

Playable

### Your emulator version

v0.5-preview-0

### psOff-libs version you are using

https://github.com/SysRay/psOff_public/actions/runs/8740145253

### Upload your log there

[20240418-171059.000.zip](https://github.com/SysRay/psOff_compatibility/files/15027658/20240418-171059.000.zip)

### Upload your screenshots there
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/977f67f9-c6af-4365-a18e-613549efea8b)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/fb4c2f6f-8747-4d76-b9ee-182ae01dfc12)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/979f8162-22ed-4f20-83f1-e72f54275137)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/d1139b14-3245-4f80-84a5-dc90e070ba88)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/adaace0a-99bc-4d88-8260-136b243bf8a5)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/ffd27333-b5ec-4d07-916b-761c7850661f)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/7151170e-3f86-4e35-b5ff-763756ef0792)
(Setting the Screen Filter to "None" in Options)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/167682fb-dcef-46d9-80f7-67d517d02884)

### Yes, I agree

- [X] Yes, I read the rules and did everything according to them

**Comment by cainan-c** [comment] 2024-04-18 16:41
Interestingly though, using the same psOff-libs as above, on Update 1.04 for the game, input doesn't seem to function at all.
Below is a video showcasing this difference between the base version `01.00` and update `01.04` (with Console and a Gamepad Viewer present):
https://youtu.be/r829mICY1aU

And as always, the logs for this session can be found below:
[20240418-173656.000.zip](https://github.com/SysRay/psOff_compatibility/files/15027912/20240418-173656.000.zip)

**Comment by igor725** [comment] 2024-04-23 20:51
> Currently, any multiplayer modes (such as Competition Mode or Player 2 controlling Tails in Mania Mode) do not work, as any controller other than the 1st isn't currently recognised.

Fixed this issue from now on you can use multiple controllers with the latest psOff-libs artifact.

**Comment by cainan-c** [comment] 2024-04-30 23:55
Popping in to update from my previous comment:
Patch 01.04 now works and colour output is also now fixed. Leaving just the filtering issues to be solved. 
Slowly making my way through the game, so far no issues. 
Currently at Hydrocity Zone with 4 Chaos Emeralds (so, ~50% game completion.)

Screenshots:
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/4d0a7f48-8746-4601-b817-b6cc38c300c9)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/4f2bc8a6-e3c2-4762-9f21-85b9fb9af920)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/fabc9521-3292-4973-8953-5fbf07b667e8)
![image](https://github.com/SysRay/psOff_compatibility/assets/30056568/e08444a8-5ba3-417f-90a0-8635e67da9be)

And, as always, the log file for this session:
https://gofile.io/d/zIn7NW
(As the archive is larger than 25MB regardless of archive type, this one has to be uploaded externally)

Expect a final update from me once I beat this game! 🙏

psOff version: Renderer version: v.0.5-nightly_29.04.24-fix
psOff libs: https://github.com/SysRay/psOff_public/actions/runs/8900061359

**Closed** 2024-09-22 11:43 UTC
Labels: graphics, status-ingame
